### ISSUE TITLE
key ring is not loaded or empty

### ISSUE THREAD

**Issue by mvfl999** [fetchai/asi-alliance-wallet#398]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

Create or restore a wallet in Chrome

### Observed Behavior

When trying to create a new wallet and after verifying the 24 word phrase and inputting the wallet name and password I get the following error:
key ring is not loaded or not empty

### To Reproduce

click "create new wallet"or "import existing wallet"  (the error I get happens with both options since I was able to create a wallet in Firefox)
click on"create new seed phrase" or "import existing seed phrase" and use the 24 word option
enter seed phrase and (verify by entering the words in the correct order)
enter wallet name and password twice.
click"next"
I get the following error: key ring not loaded or not empty

### Version

0.19.0

### Environment Details (Optional)

```markdown
windows 11
Google Chrome  Version 128.0.6613.138 (Official Build) (64-bit)
ASI chrome extension version 0.19.0
```

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@mvfl999

**Comment by abhifetch** [comment]
Hi @mvfl999 ,

can you please reinstall the extension. This should resolve the issue. 
If not please get back to us here. We will resolve it for you.

**Comment by JulesFL** [comment]
Hello. I have the same problem. I just wanted to install the ASI Chrome extension after reinstalling Windows 11 and I keep getting the error message "key ring is not loading or not empty". Before, everything worked fine. I reinstalled the plug-in and it still doesn't work. I can neither create a new wallet nor integrate an existing one. It works via the Android app.

**Comment by sh-wallet** [comment]
Closing this issue as it has been resolved in ASI Alliance Wallet v0.19.3.
